### ISSUE TITLE
(user): Change affichage page d'accueil

### ISSUE THREAD

**Issue by GarciaPena-Loris** [EcoTrackerApp/ecotracker-android#32]
**Description de l'utilisateur concernée**
Utilisateur de l'application

**Fonctionnalité demandée**
Changer l'encart principal par :
"Du _06/05_ au _18/05_, vous avez émis **5.45 kgCo2**,
                 **Vous êtes dans la moyenne**,
          Continuez comme ça, c'est excellent !"
Et enlever le texte sur l'image.

**Raison**
Je pense que ça sera plus propre

**Comment by Shyrogan** [comment]
Je ré-ouvrirai si j'ai le temps et si on est tous d'accord que c'est nécessaire je pense
